---
- stat: path=/etc/sysconfig/network-scripts/ifcfg-{{ routing_network_interface }}
  register: ifcfg

#- debug: msg="default ipv4 interface is {{ routing_network_interface }}"
- debug: var=hostvars[inventory_hostname]
- debug: var=ansible_routing_network_interface
- debug: var=hostvars[inventory_hostname][ansible_routing_network_interface]

# This is a hack to make the NM interface name known, so we can add a route file
- name: Set up a network config file
  template: src=ifcfg-dev.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ routing_network_interface }}
  notify:
          - apply changes
  when: ifcfg.stat.exists == False

- name: Set up a static routing table
  template: src=routing_table.j2 dest=/etc/sysconfig/network-scripts/route-{{ routing_network_interface }}
  notify:
          - apply changes
