---
- name: Install bridge utils
  yum: name=bridge-utils state=latest

- name: Create kubernetes bridge interface
  template: src=ifcfg-kubernetes-bridge.j2 dest=/etc/sysconfig/network-scripts/ifcfg-kubernetes-bridge
  notify: restart network service

- name: Bring up kubernetes bridge 
  command: ifup kubernetes-bridge

- name: Configure docker to use the bridge inferface
  copy: src=docker dest=/etc/sysconfig/docker
