---
- name: Determine if Centos 6 
  shell: "grep 'CentOS release 6' /etc/redhat-release"
  register: is_centos6
  ignore_errors: yes
  changed_when: false

- name: Determine if RHEL 6
  shell: "grep 'Red Hat Enterprise Linux.*release 6' /etc/redhat-release"
  register: is_rhel6
  ignore_errors: yes
  changed_when: false

- fail: msg="this playbook only supports RHEL 6.x/Centos 6.x !" 
  when: is_centos6.rc != 0 and is_rhel6.rc != 0
