---
- name: make sure docker is installed
  yum: pkg=docker-io enablerepo=epel state=latest
  notify:
          - restart docker 

- name: write the config files for kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  notify:
          - restart kubelet

- name: write the config files for proxy
  copy: src=proxy dest=/etc/kubernetes/proxy
  notify:
          - restart proxy

- name: write the upstart conf files for minion components
  template: src={{ item.bin }}.upstart.conf.j2 dest=/etc/init/{{ item.bin }}.conf 
  with_items:
          - { bin: 'kube-proxy' }
          - { bin: 'kubelet' }

#- name: Enable cadvisor
#  service: name=cadvisor enabled=yes state=started

- name: Enable kubelet
  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started
